### ISSUE TITLE
Split manual into separate repo

### ISSUE THREAD

**Issue by MattMS** [ramda/ramda.github.io#128]
As was done for the REPL, and considering work on it has stalled, would it be worthwhile moving the manual into a separate repo?

This would also allow removing the gitbook dependency.

**Comment by buzzdecafe** [comment]
frankly i don't know enough about the manual to say on way or the other. Apart from removing the gitbook dep, what other advantages do you see? And how would we build the whole site at release time?

**Comment by MattMS** [comment]
Building the site with multiple repos would be tricky, I guess it could be done with a Git Submodules.

I was mostly thinking of a way of parking the manual until it is decided to actually be incorporated into the site.

**Comment by buzzdecafe** [comment]
I am relying on your judgment here, since I am not familiar with the manual. So maybe we need some input from @CrossEye ?

**Comment by MattMS** [comment]
The last significant work seems to have been from a year ago (ignoring a small fix 2 months ago).

If it is to be continued (as I hope it is), then it would be easier to keep it in this repo.
#107 would help with a bit of cleaning too.

I was prompted to open this issue due to the [previous issue on planning sections](https://github.com/ramda/ramda/issues/1282) being closed.

**Comment by buzzdecafe** [comment]
ok, let's keep in this repo, but move out of version folders. there is no reason we should build another one with every release

**Comment by CrossEye** [comment]
That issue was closed simply due to the lack of activity.  I've started writing again, on several unrelated topics, but when I'm done with those (maybe three weeks) I'm hoping to start writing about Ramda again.  I will reopen that issue then.

As to a separate repo, I would want to know why.  I have no objection so long as we can comfortably build the whole site in a simple manner, but I don't see the point.

**Comment by MattMS** [comment]
Sounds awesome, and I'm more than keen to help if I can!

I think it will always be more complicated to build the site from multiple repos.
The only benefit would be that the manual and the API have different requirements, but not enough to be a major issue.

Happy to keep this closed!

**Comment by CrossEye** [comment]
That issue was closed simply due to the lack of activity.  I've started writing again, on several unrelated topics, but when I'm done with those (maybe three weeks) I'm hoping to start writing about Ramda again.  I will reopen that issue then.

As to a separate repo, I would want to know why.  I have no objection so long as we can comfortably build the whole site in a simple manner, but I don't see the point.
