### ISSUE TITLE
offline support

### ISSUE THREAD

**Issue by iamstarkov** [ramda/ramda.github.io#16]
thanks for great lib

i frequently developing offline so i’m using readme in node_modules as API docs, but ramda doesnt have it. it makes me kinda sad

also one of solution is to add offline support to ramda docs

**Comment by davidchambers** [comment]
> one […] solution is to add offline support to ramda docs

I like this idea. We could add support for the [application cache][1]. I once contributed to [brunch/appcache-brunch][2], so I have some experience with it.


[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache
[2]: https://github.com/brunch/appcache-brunch

**Comment by iamstarkov** [comment]
is there any news here?

**Comment by davidchambers** [comment]
Nothing to report at this stage. I'm not happy with the current process for generating the documentation; I'd like to simplify it before adding functionality. This will take some time, but adding a cache manifest to the build process at that point shouldn't be too difficult.

**Comment by iamstarkov** [comment]
so… will you add cache manifest?

**Comment by davidchambers** [comment]
I've nothing to add to my previous comment at this stage. Pull requests welcome. :)

**Comment by branneman** [comment]
I'd be careful with *simply* adding a cache manifest, application cache has a lot of gotchas: http://alistapart.com/article/application-cache-is-a-douchebag

@iamstarkov: Since this is probably going to take a while, I'd suggest cloning this repo and just running the docs locally for your offline usage. That way you even have relatively easy access to older versions of the documentation. It could look like this:
```
git clone https://github.com/ramda/ramda.github.io.git
npm i http-server -g
http-server ramda.github.io/0.17
```
Whenever offline, you can always run that http-server command, then browse at http://localhost:8080/

**Comment by davidchambers** [comment]
Thanks for the suggestion, @branneman!

**Comment by MattMS** [comment]
Should this issue be closed?

I think the current standard for offline support is with [Service Workers](https://developer.mozilla.org/en/docs/Web/API/Service_Worker_API), but that requires HTTPS, which we cannot currently use with GitHub Pages on a custom domain.

The documentation package has `http-server` as a dev dependency, so you can simply do `npm i && npm run server` to run the website locally.

**Comment by iamstarkov** [comment]
sure, lets close it
