### ISSUE TITLE
FR: Switch to Babel on web REPL.

### ISSUE THREAD

**Issue by hemanth** [ramda/ramda.github.io#32]
^

**Comment by CrossEye** [comment]
I would be all for it.  We didn't put much effort into creating this REPL initially.  I say that, and I should clarify: _I_ put no effort in whatsoever.  @buzzdecafe did all the work, as I recall.<sup>1</sup>  But he started from a very similar REPL made by a friend and former coworker of ours.  It got tweaked enough to get it to work, and we haven't done much since.  

In the past several weeks there have been a number of wonderful alternatives published, and I hope we can combine some of the best ideas from many of them into an updated version of this.  Babel would be a good start.



----------
<sup>1</sup>I take it back.  I helped a tiny bit with the URL shortening code.

**Comment by hemanth** [comment]
Cool, I am all up for it.

**Comment by buzzdecafe** [comment]
i believe this is the case now; this may be ok to close?
