### ISSUE TITLE
Move manual pages into own folders

### ISSUE THREAD

**Issue by MattMS** [ramda/ramda.github.io#52]
Would there be any issue with moving each of the manual pages into their own folder, with the content stored in a `README.md` in each?
This would allow an `index.html` to be generated from each `README.md` and sit beside it for serving to the web.

For example, in [manual/01-intro](https://github.com/ramda/ramda.github.io/tree/master/manual/01-intro), `Composition.md` would be moved/renamed to `Composition/README.md`.

**Comment by CrossEye** [comment]
The manual has stalled, but the design has been to use [gitbook][gb], which to some extent dictates the layout of the files. Because we're not very far along, we don't advertise the manual anywhere, but it is actually online at http://ramdajs.com/0.19.1/manual/.

There is [an issue][rm] to track the progress of the manual.  Any help would be welcomed!



  [gb]: https://github.com/GitbookIO/gitbook
  [rm]: https://github.com/ramda/ramda/issues/1282

**Comment by MattMS** [comment]
Oh nice! I haven't seen GitBook before, looks pretty cool.

I'm glad to see work on this type of documentation.
It definitely fills some of my own confusion with the current API docs.
