### ISSUE TITLE
Move fonts and styles out of version folders

### ISSUE THREAD

**Issue by MattMS** [ramda/ramda.github.io#63]
It seems unnecessary to have the same files in each of the version folders.

Would there be any problems with moving the font files and `style.css` into a common folder?

This would simplify the make process too.

**Comment by buzzdecafe** [comment]
sounds good to me

**Comment by raine** [comment]
If #33 could be fixed while we're at it would be great.

**Comment by CrossEye** [comment]
:-1:

I'm a little concerned that not including them would cause problems if we start doing any level of redesign.  If version 0.22 has a significantly different look from 0.21 and it involves (even minor) change to our JSDoc tags to accomplish it, then we will start having problems.

Of course doing this would help fix #33 directly too, assuming we could point to these files relative to the root.  But we could also solve that by copying the latest version of these files into the root when we create a new version.  I think I'd rather do that, at least for JS and CSS.  Font files should be static and could move to a permanent spot, I suppose.

**Comment by buzzdecafe** [comment]
I don't think we should constrain ourselves for some redesign that may happen at some time in the future. I'd rather simplify now. if we redesign later we'll deal with upgrading the legacy stuff at that time.

**Comment by CrossEye** [comment]
I guess what I'm suggesting is that what we have now is actually simpler, even though more verbose.

Do you want the 0.17 docs?  They're in the folder 0.17.  The ones for 0.19.1?  They're in the folder 0.19.1.  I'd rather that than "Well, you take folder 0.19.1 and zip it together with the CSS folder, the JS folder, and the font folder from the root..."  I'm not thinking about any particular redesign, but I've considered several minor ones that involve changing the JSDoc template and the JS that runs on the page in coordination; there would likely be some CSS work too.  It's easy to do that without worrying about breaking older versions if I get my own structure to work in.  Otherwise I have to consider how it affects 0.8 and 0.13 as well.

**Comment by raine** [comment]
My gut feel is that we're better off if the version-specific directories are entirely self-contained.

**Comment by MattMS** [comment]
Since the `less` and font sources are not contained within the version folders, they do not seem entirely self-contained.
Any changes to previous versions would require some git trickery, would they not?

I guess the alternative to this request would be moving the source files (maybe even `package.json`) into the version folders.

**Comment by CrossEye** [comment]
> Any changes to previous versions would require some git trickery, would they not?

They would.  But I am not worried about regenerating old versions.  If we had to do that, it would be one-off, and granted, fairly obnoxious, but my thought is that they should just remain static.

I guess I'm not worried about the source files.  I'm not overly worried about previous versions' docs, I guess.  I want them around, but I don't expect them to get a great deal of attention.  I suppose some of that might change after 1.0.

**Comment by MattMS** [comment]
All seems fair enough. :smile: 

So was that yes to moving font files and no to `style.css`?

**Comment by CrossEye** [comment]
Well, we'll see what others say.  I would probably just as soon keep everything self-contained, though, myself.

**Comment by MattMS** [comment]
So it seems #88 starts work to closing this issue?

**Comment by CrossEye** [comment]
This probably should have been closed long ago, as no one was doing anything about it.
